server:
  port: 9090
---
spring:
  cloud:
    gateway:
      routes:
        - id: people
          uri: http://${PEOPLE_HOST}:${PEOPLE_PORT}/
          predicates:
            - Path=/api/people/**
          filters:
          - name: AuthPreFilter
        - id: auth
          uri: http://${PEOPLE_HOST}:${PEOPLE_PORT}/
          predicates:
            - Path=/api/authenticate
        - id: user
          uri: http://${PEOPLE_HOST}:${PEOPLE_PORT}/
          predicates:
            - Path=/api/user/**
          filters:
            - name: AuthPreFilter
        - id: songs
          uri: http://${SONG_HOST}:${SONG_PORT}/
          predicates:
            - Path=/api/song*/**
          filters:
            - name: AuthPreFilter
        - id: website
          uri: http://${SITE_HOST}:${SITE_PORT}/
          predicates:
            - Path=/**