server:
  port: 9090
---
spring:
  cloud:
    gateway:
      routes:
        - id: people
          uri: http://localhost:8080/
          predicates:
            - Path=/api/people/**
          filters:
          - name: AuthPreFilter
        - id: auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/authenticate
        - id: user
          uri: http://localhost:8080/
          predicates:
            - Path=/api/user/**
          filters:
            - name: AuthPreFilter
        - id: songs
          uri: http://localhost:9000/
          predicates:
            - Path=/api/song*/**
          filters:
            - name: AuthPreFilter
        - id: website
          uri: http://localhost:3001/
          predicates:
            - Path=/**