server:
  port: ${GATEWAY_PORT}
---
spring:
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
      routes:
        - id: people
          uri: http://${PEOPLE_HOST}:${PEOPLE_PORT}/
          predicates:
            - Path=/api/people/**
          filters:
          - name: AuthPreFilter
        - id: services
          uri: http://${SERVICES_HOST}:${SERVICES_PORT}/
          predicates:
            - Path=/api/churchservices/**
          filters:
            - name: AuthPreFilter
        - id: churchmusicteam
          uri: http://${MUSIC_TEAM_HOST}:${MUSIC_TEAM_PORT}/
          predicates:
            - Path=/api/churchmusicteam/**
          filters:
            - name: AuthPreFilter
        - id: auth
          uri: http://${AUTH_HOST}:${AUTH_PORT}/
          predicates:
            - Path=/api/churchauth/authenticate
        - id: user
          uri: http://${AUTH_HOST}:${AUTH_PORT}/
          predicates:
            - Path=/api/churchauth/**
          filters:
            - name: AuthPreFilter
        - id: songs
          uri: http://${SONG_HOST}:${SONG_PORT}/
          predicates:
            - Path=/api/churchsongs/**
          filters:
            - name: AuthPreFilter
        - id: churchtg
          uri: http://${CHURCH_TG_HOST}:${CHURCH_TG_PORT}/
          predicates:
            - Path=/api/church-tg/**
          filters:
            - name: AuthPreFilter
        - id: churchsongbook
          uri: http://${CHURCH_SONGBOOK_HOST}:${CHURCH_SONGBOOK_PORT}/
          predicates:
            - Path=/api/songbook/**
          filters:
            - name: AuthPreFilter
        - id: sheets
          uri: http://${SONG_HOST}:${SONG_PORT}/
          predicates:
            - Path=/gdrive/sheets/**
        - id: website
          uri: http://${SITE_HOST}:${SITE_PORT}/
          predicates:
            - Path=/**